language: python

env:
  - TOXENV=py34

# Python 3.5 has to go here until Travis adds it to the default build images.
# https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35

sudo: false

install:
  - pip install pytest
  - pip install tox 
  - pip install coveralls
  - pip install -r requirements.txt

script:
    - tox

